name: Tests

# Run tests on push to master and all pull requests
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: 'Create env file'
        run: |
          touch .env
          echo RESTFUL_PORT="8080" >> .env
          echo INFURA_API_URL=${{ secrets.INFURA_API_URL }} >> .env

      - name: Build Containers
        run: make build

      - name: Run Containers
        id: run-services
        run: make up

      - name: Run Unit Tests
        run: make tests

      - name: Run Benchmarks
        run: make bench